[[Tasmanian]]
arch = "aarch64"
git-tree-sha1 = "d69d42e6c65e27f63038af1db124097b698a9466"
os = "macos"

    [[Tasmanian.download]]
    sha256 = "a1b31387e6588478ea8841daeaebf5c9a5aae74e4570fb94e69941d096e56d6e"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-apple-darwin.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad03981984f3056133cb82dfb2d7bd8721ebb21f"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "5c9c664b70c8ced3e44d1362ae16433429e50b6dcaa3b51407a145546ecdf7e9"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e3bcd0d63f784ac07c923c0aa6be8fc56a7dba7"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "46696fb3d206ef0da82eab3a83b30423e3f3a52bb93201a34bf78994cf73da77"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf080d32837a748979faabb2ad35634897a4edc6"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "81a4a920efd2463423a8c7bf17559d844cb52404a2d7ac73da316a18004ebef5"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41c5fe54ed87789e2da75dfff969f885e4e5d8a8"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "591feea64d25e2f13c91c9f6b09abe4bc54f54f9f23bd52a9c59bb397f7f19ae"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "aarch64"
git-tree-sha1 = "1a9bc7010e9ae87cda78ab186e15afc885de4d62"
os = "freebsd"

    [[Tasmanian.download]]
    sha256 = "3cb7ed03143452f3c793bad46a1ff7bd9d50618a2b453afa742744f4164d3b79"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.aarch64-unknown-freebsd.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b48273c4c3a60cf11c9c6f1a0d8d862856d6cbad"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "5fee80ed735abaac5943992488968cff5e020a6e7b2cfa8ded4fc9af68299083"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b0493c94a5ca4fb7688064234eb856f096d8686"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "f87cc006833476a273a9d58d5a7a57fcda29bd36da1ec41e53508099b8588d55"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c7256612aaa9be306b5689f88296b81d2a7222f"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "9403505e92288c8eadf1b255b5af3a3611fda0cd399a219af151d86f0565a173"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92d320f6e5f3e38fbeccb6c1c1283cb79099f147"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "23028973e9790a5bac04af8d256fe65d6316932277fa39acb504675c86d1ac74"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ce8a8dad59645a4d3ea44aaf2b5f73333bbea0e"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "4dbba8ad55ce48ec7f32b7b4f12491d649c094766e149da3668f250e42d4a138"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcef1325ce42438ffb2296741c3b9f3360808290"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "0cf78ae39b597e8d72fa10f915d0dce128494602dfe3b355753facad68ef183a"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99bf36a5a1e482a233f21a55bd5197dc641c9b51"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "73282d7b0a598537b97b0fd3d72e7a975b296d3f5be2823f761254afc2ce2db6"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9a0c6d60512bd22125cba89dc4e77a5a75c1834"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "11af57b7580a8fd8ea24ec2710435a85dfa859435111fedacb707b0cf6198af5"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c16f7c68578cc2c54db2d22560cd680b64fae17"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "5a7e7a5cca5efce5b1970faa9eade8ecfd109dfc165947cfe91198b3f8433d45"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78be928eab538d6cf93f7bbd55690087f7f9e216"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "e4bf5230ec3f8bc3ef4803d23897679081b3a633d74ff9d66c03a82ddbc3101d"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6402a4b53fc355e4f97592facb5f9045ce03949"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "b56831f69f0b452ee0e8a738e8c29d4854d3619555568ddeb509a5d16c122656"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cf319997691f40748fefed9fa6206ba4e525fb3"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "4b4de18f56058fe41ab3dd787969d8f210b135590b0b0967ad28486b57d5f994"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f05fff9ed5020b5413e6b8a5a1d8a2141f10b18e"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "98857ce8d1dede0d256f276a28e8022027e96bdf95ba5ba5f720c8ad10474d4c"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aafc0e90e6f27c695c8affb419589278decf99b8"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "cb77d257799bf39b0cb7ee7e66256d1665ffa14fe0dc467d35cb70e0ec14546d"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[Tasmanian]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89e765e14dade6fc656c6698e127fc2ac52ae2c8"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "1be7d10f60a0513432028ad4ed93970291e899476ced3c092d81847c30daca6a"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59535b6505b53e2c91339da83b85434f9d327d0d"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "9ee59112fa36e2db3f8463c5d8702926a8e7d68eddb6011e99bebd6b47fd1537"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "927a28dde746eea61b9a425b7e315c0cb4537b83"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "b9a1509be0e3ff085129c908cddfd54d6a68c878bc23543cfe69d42a1059b417"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7d22c5dff00af15f3916c948d24e3825dbcddc5"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "b7f4b3ed2556f35919a9077b3413fdce06f546c761d513da014fbbf2a43734e2"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
git-tree-sha1 = "c0a879b92f29f724748e6769c6828916582b2d38"
os = "macos"

    [[Tasmanian.download]]
    sha256 = "c77628d9fee0d3ca917bdd19a023145b1939644e069cdfb94d260772fbaa75ba"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-apple-darwin.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68ac5107290bba4a4bc26605ff8ebdf9d870c21a"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "f5f5be0db5566216b6957eb00f782d423073f2a6196845032be81e4b764d8efa"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27c452c602ba397c16be7fb8c0369dbd081c122b"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "02f0183641c44ad24ea5dbc045db97f0ff765c3e0887a59ef6c4101dd71c14dd"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b12da550c6d1ec3263bc03d6a41ef9f442c5a165"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "55b7abf2b400c4fdbfb956a4c5858c711017ccd9857429d1215143dfed2bcb0a"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06eccb869729661f8d9308945100097e2a7f53c5"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "8ef76cd0872649f0873d6282d20bc69aa0abee73bc4a8bb18e8b097a3b3dec84"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
git-tree-sha1 = "64d04d51219aaa13355c940e991e846590d7d014"
os = "freebsd"

    [[Tasmanian.download]]
    sha256 = "26df53832d3d1691dd7e14ba0bd57d2460f47a2c6a57498680a92d447fca4762"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-unknown-freebsd.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b629725d1aa15ef458cff8df95ab0d5df1e3dbf"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "1cf34311e91a65477ee264b77aec628cd9e7d1baf80e33e167266e823278f578"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc4e07347750e05106561b32b01d17cf4be983ed"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "78d534237a50801cf2b5446a570cbb67dd5377f22527ab23399dd66abe52985a"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.1.0+0/Tasmanian.v8.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
