[[Tasmanian]]
arch = "aarch64"
git-tree-sha1 = "689208659bdf9cb5d6ca15f46d152f42e16c7245"
os = "macos"

    [[Tasmanian.download]]
    sha256 = "f3f2c8e09442bca8de81f1240474041bae7d0e442e6b6a2c55c49e8d0164b986"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.aarch64-apple-darwin.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bef335ce36fbb81693f4072db6bba64b949f7900"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "803ae059ba096888224cd560f013d24ac1e6b0fa005fac3e42c2fbdbd2c73de3"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6e69df54bde042d6788657566172704cee82ade"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "a7f4549a29244ebf9fa01b4457aad21404f1035cef71b2171f6958f84e5fa233"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "122183d4056b4d7cbd08001aa2c7dd0907e4e053"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "0afe45f435a5293008624da6bcedb45bca6bb30ac58dc425a999d790f724ee75"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aed77b6dda726342d063a65f2893c7519247f215"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "92ae840ad49ccef1818746b1501ec15eda3d944713d4d2af4ab59c6c67cbbde4"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "098feb845e140df93e5d932bb415ac6b5673aa46"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "adcfbb2e3031f5e78c4679bfda351cf78ccd44f2f1ae259f380a983c2701f994"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "306355df7c1639b771992c357427126408ab6b12"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "706dbceeaeca60ec6164bd4a143325ac4ec7f9ff569d3a4eae7bca44247203e1"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44d03e914bbfbd3cfb44ec6a88f54b3925c89a15"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "02ff141037921a6a4dbafad54b7ed92c02c6331b085c0c0fcb16df8b154fb088"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cb00e266a5b974615af40d61ff5d3ccf46a9f52"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "5a4ba1dbbe78967b8bc481554838a04cc211828244b2c684ee4dd5301cb76adc"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b64fe904ca74c186ee4b3e42c9d91c3b77c77f36"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "a47b4e02cc3b630427977c97dfcc21e7f648d434f3cd13b444f5308c582f0487"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d10e2491c01553d9ea3cffd8a4bb2d4df9f91cce"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "e609ce1206abd7a764f729e3890c1695fb24c710b0168b809b322d9ef5e5da33"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d6593aec08273083446460394d25e0e22632c30"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "904cc7c8c0da5432fc4e14dcd446bb4db8b4cc65a40f7f79fd8aba285a0aada7"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Tasmanian]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c644f9c8d1c78de534aa6159d5dd7843fbd338c0"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "4e330e0469398f0aa6ed253219b68362d52c449780869c470edeaae29babd917"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e11b595e7a10ab2315a605f4bba4713f3e06a53a"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "52d6e348edd42bf85a1d02f1d66f998cfd56de7d74ff874972dee2cca58983c1"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "997e539a5b070c0390cb2a7e646ed04f893c0cbf"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "152ed9b0b8d9c1db44d26db47dcf4116a027d0ed2dd32bf3866b85adc9285852"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd25c9c1c3c9b7c70f18eb0e9b18dc5c9e19aaa"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "a866bf62f1c20a5abac9be5230c3c26c6ac65a8f064e7a9ec1df5526b65f2686"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff7b7337ce1c48501291021d0ace38c1979b62d"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "fb9d6ebf5033fbe9ae3576ef4128ce9f26956fea977c5510761e0b723d0e1435"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c09da0bf7e58c650c6f58a909504d54d49befeb"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "c5968e6d52c173b9bd4430d846b567f312a69d22f1bf968e0ad41843c7f4b5e5"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Tasmanian]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3544228690f4d4ed808c3a8ce6862b62e385344d"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "52f4e48a6296b706957ec4aed8847637ec23e8e426e02843af5c69d940a858a6"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Tasmanian]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b38a370f45b127fc6c44ceb7c3d035ffb5bea13"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "1d9d4ce5d68f18de33ce240e469be83c5416368e305f29b2f784a6d30c7c5aa6"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8d1c469e0ae2d422a250379274984749a6a2bfc"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "850cc39c73aa878a963cca4daf5d4dfc06531ec8cff6f3000fbaa80d0d09d3aa"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
git-tree-sha1 = "aac739028f41e79dbe84358674dc36e66df5a333"
os = "macos"

    [[Tasmanian.download]]
    sha256 = "d66c5be5000068d8cde0653c739b4a2199488c1aac0118a6c4b2799318a95f7f"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-apple-darwin.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9ebacd280b2972d6e9b0102ce2438af8ca45cbf"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "d67cba3fb62078949779fd53874aada1db09affb14b460324e7fe7caee356962"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ded1951b7109d4a7ed177e4fab87de0450869b2a"
libc = "glibc"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "3b3bb7f99c927e0b044723e6b85db858349d00af7ddb3426b351fd63a2052b90"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4cae91b4b932fd5c3530dcc78a76c4799fcd03c"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "223518f61f092c616a23ca5a4d3fa8ad0e9c143bb6b234e05b9f03d6d15a13eb"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6fd9cfb1c8220935499cdacc9ff0909b49fc0df"
libc = "musl"
os = "linux"

    [[Tasmanian.download]]
    sha256 = "73329d07f388fa73f8ef0fcc7dd5751506851e907d7fb6467eac7c304b8cb570"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Tasmanian]]
arch = "x86_64"
git-tree-sha1 = "c8906540ec45c5e0bb054ff4dde86883ee5a4b67"
os = "freebsd"

    [[Tasmanian.download]]
    sha256 = "11d3d96a58d0f3fe290e896702df705b4219631b86881e70cb8fd92167a59fd9"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-unknown-freebsd.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fa1a91b0bf31b05079d899ee7489e49736180e4"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "30d3394bf0b09a491a4bba65b843440d1c805ee376462d5222aab75badc45ede"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Tasmanian]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d7d2cde531bfde5d4a65a1beff480eea318842f"
os = "windows"

    [[Tasmanian.download]]
    sha256 = "d2ab31633d18134d3c8c74fc4e7709c5515ed3e76475242126435646261dfc94"
    url = "https://github.com/JuliaBinaryWrappers/Tasmanian_jll.jl/releases/download/Tasmanian-v8.0.1+0/Tasmanian.v8.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
