# Autogenerated wrapper script for Tasmanian_jll for armv7l-linux-musleabihf-cxx03
export libtasmaniandream, libtasmaniansparsegrid

JLLWrappers.@generate_wrapper_header("Tasmanian")
JLLWrappers.@declare_library_product(libtasmaniandream, "libtasmaniandream.so.8")
JLLWrappers.@declare_library_product(libtasmaniansparsegrid, "libtasmaniansparsegrid.so.8")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtasmaniandream,
        "lib/libtasmaniandream.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtasmaniansparsegrid,
        "lib/libtasmaniansparsegrid.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
